### ISSUE TITLE
Technical Approach Document

### ISSUE THREAD

**Issue by awright** [hotosm/visualize-change#1]
Let's record progress towards this deliverable here.

**Comment by szymonkaliski** [comment]
Hi @awright what would you like to see in technical approach document? Is it technologies used, how components are connected together, some diagrams of message/events flow, or all of the above? :)

Hopefully this document can be a "live thing" since I'd prefer not to set everything in stone so early in the dev process...

**Comment by awright** [comment]
@szymonkaliski i am thinking this is evolving articulation of the work plan. so definitely a living thing! at this stage, i think we want a clear overview of approach and architecture. for some reason, i am imagining a flowchart. 

ideally, this document can serve as the core of final documentation.

**Comment by awright** [comment]
readme is evolving document with technical approach. 
https://github.com/hotosm/visualize-change/blob/master/README.md

**Comment by awright** [comment]
PS I am going to keep this open so we can continue to understand this as a priority. I will also offer some other projects that a nice structure for documentation that we can use as a reference on #15 
@smit1678 do you have any suggestions here? I think you originally recommended OAM?

**Comment by smit1678** [comment]
Yes, and there are some examples in OAM (https://github.com/hotosm/OpenAerialMap/issues/14, https://github.com/hotosm/OpenAerialMap/issues/25, https://github.com/hotosm/OpenAerialMap/wiki/Catalog-API---Browser:-Initial-Strategy-and-Approach) and then there is a recent example from the website redesign: https://github.com/hotosm/hotosm-website/issues/130. Main goal is to capture the approach (not just a rundown of structure) and what are the main goals and considerations. Framework and libraries are a part of this but also want to know about deployment and hosting considerations.

**Comment by awright** [comment]
The OAM documentation outline seems very thorough and I've provided an outline of that structure in our Documentation ticket #17

**Comment by szymonkaliski** [comment]
For now, README.md is being kept updated as we go, and should be treated as a technical approach document.
