### ISSUE TITLE
Emailing MP4

### ISSUE THREAD

**Issue by awright** [hotosm/visualize-change#19]
to execute on the user workflow #2 we're going to need an email sending service to use. @smit1678 who do i contact to set that up? cc @szymonkaliski

**Comment by szymonkaliski** [comment]
Well, I think we're not going to be emailing MP4 as attachment, but just a link to download the rendered MP4. We still need some email service to handle that, it's not a blocker right now, but we need that to finish the "core flow" for end of February.
