### ISSUE TITLE
Github Issues simplification

### ISSUE THREAD

**Issue by szymonkaliski** [hotosm/visualize-change#20]
@awright I think we have way to many issues for now :)

Would it be possible to combine all the renderer related ones (#4, #6, #8) into one and all the frontend ones into single one (#7, #9, #11)?

**Comment by awright** [comment]
@szymonkaliski These tickets are listed as specific deliverables in the contract, so I'd like to keep them even if they don't all serve as active histories of our work. Let's see where we can simplify though moving forward.
