### ISSUE TITLE
server requirements for underzoom generation

### ISSUE THREAD

**Issue by szymonkaliski** [hotosm/visualize-change#23]
OSM QA tiles are zoom level 12+, if we want zoom levels 0-11 as well, we need to generate those underzooms. I can do that in good quality using:

```tippecanoe-decode tiles.mbtiles | tippecanoe -f -pf -pk -ps -b0 --no-tile-stats -l osm -Z0 -z12 -o tiles.out.mbtiles```

For just the Indonesia tiles, this takes about 1.5hrs on 2.2GHz i7 with 16GB of RAM. Indonesia tiles are about 500mb, and grow to about 700mb after adding underzoom.

Whole planet tiles are about 28GBs, so by simple (probably inaccurate) math, processing this on that machine would take 84hrs, so this is pretty much unacceptable, if we want to have daily tiles updates.

The test server we currently have has 1CPU and 2GBs of RAM, so I'm not even trying to run that job there.

**So, for final version, we either need much much beefier server, or ignore the underzooms, and allow users only to generate renders with zoom levels 12+.**

I'll keep the underzoom generation scripts in code for now, but will comment them out, so we can get back to this any time, but I think we should discuss the server requirements here.

**Comment by szymonkaliski** [comment]
We now have `tile-processor` docker container running cron job to download daily `latest.planet.mbtiles`, it has optional `GENERATE_UNDERZOOM` env set to `0` right now: https://github.com/hotosm/visualize-change/blob/f871c7d11a3b22567844322d7fcc0bd2b87cfd93/docker/docker-compose.prod.yml#L10

**Comment by awright** [comment]
@szymonkaliski any outstanding issues here? can we close?

**Comment by szymonkaliski** [comment]
The issue is still here, nothing has changed. We have the functionality to generate underzoom, but this is very slow and cpu/hdd heavy process, and it doesn't make sense to run it on our current server. I marked this as discussion for possible other solutions, or at least settling on "no underzoom" solution.

**Comment by awright** [comment]
Summary: users currently can only generate renders with zoom levels 12+. We would need to pay for more server space for lower zooms. 

@smit1678 We need an OK that 12+ is cool?

**Comment by smit1678** [comment]
> @smit1678 We need an OK that 12+ is cool?

👍 from me. Settling for z12+ is a good approach for now. @mojodna and I reviewed as well and thought that this is best if we punt on figuring out how to speed up processing for now. There are more priority discussions around UI that are worth getting right. 

Since we're limiting to z12, we'll want to make sure we factor for this in the user experience so it's clear that this is a limitation of the tool at the moment.

**Comment by szymonkaliski** [comment]
So it looks like we are agreeing on current state of z12+, so closing this issue for now :)
