### ISSUE TITLE
smtp provider for email notifications

### ISSUE THREAD

**Issue by szymonkaliski** [hotosm/visualize-change#24]
For sending email notifications we need some SMTP provider, email-sending is part of the "core flow" we aim to get at the end of February, so to implement this, it would be great to get something in the next week-two... @smit1678 ?

**Comment by smit1678** [comment]
We have a mailgun account that we should be able to use. What do you need to get started?

**Comment by awright** [comment]
see #1

**Comment by szymonkaliski** [comment]
with commit https://github.com/hotosm/visualize-change/commit/255f8c28e9245f1fb398396814a61bc31f5fceb0 mailgun email sending is supported, proper `env` has to be set before building and running: https://github.com/hotosm/visualize-change#env
