### ISSUE TITLE
Processing Alpha Version

### ISSUE THREAD

**Issue by awright** [hotosm/visualize-change#3]
This initial prototype of the Mapping Visualization functionality will include basic implementation of:

- [x] Queuing
- [x] Exporting
- [x] Offline render

As stated in the proposal: 
"this phase we will focus on implementing alpha version of the application including basic
frontend UI and working backend API including queuing and exporting. We will use this
version for internal testing, to find UX problems, and debug possible issues with backend."

**Comment by awright** [comment]
First version! Found here: https://github.com/hotosm/visualize-change

Includes:
- end-to-end workflow 
- very basic frontend where you can select lat lng and timespan and trigger render

The server reacts to that render endpoint and pushes message to queue which is picked up by renderer, and final mp4 is created!

@szymonkaliski currently working on developer experience to make dev as smooth as possible and document in places where it's not smooth

**Comment by szymonkaliski** [comment]
Should we close this issue since it's completed?

**Comment by awright** [comment]
I think we can complete this but would like to review together at #21 meeting. 

@smit1678 can you give approval as well?

**Comment by szymonkaliski** [comment]
So to recap, we have end-to-end workflow working (https://github.com/hotosm/visualize-change/issues/3#issuecomment-360844216) and our next steps are:

- get some feedback on UI wireframes, then designs, then implement them (https://github.com/hotosm/visualize-change/issues/2#issuecomment-361926613)

**Comment by smit1678** [comment]
> @smit1678 can you give approval as well?

👍  yep, tested locally and it works well.
