### ISSUE TITLE
Add dev url to test server

### ISSUE THREAD

**Issue by smit1678** [hotosm/visualize-change#30]
@szymonkaliski Can we put the test server behind the `dev.visualize-change.hotosm.org`. I've pointed the url at the server so we just need to hook that up through the deployment.

**Comment by szymonkaliski** [comment]
Yeah sure, I'll do that in a bit, for now you can access through dev.visualize-change.hotosm.org:8080

**Comment by szymonkaliski** [comment]
Done, url should work on port 80 now
