### ISSUE TITLE
Usability Testing

### ISSUE THREAD

**Issue by awright** [hotosm/visualize-change#32]
We are looking to test current functionality of the site, specifically with the stakeholders in Indonesia (via @mataharimhairi). To support that, I drafted 6 questions. Would like to review and settle on a common set of questions we can use as a template for comparison. Link to the following [here](https://docs.google.com/document/d/1AszqsUXq-Narg-MXec5VK9OqTjSxfkzuSYs0TCwaV4A/edit?usp=sharing) cc @szymonkaliski @smit1678 
***
### Potential Questions:
We want to see if everything is there the user expects for a OSM Animation tool. So the following are open-ended questions for us to test if the intent of the tool is clear and aligns with what they would expect to find.

Note: We agreed to really focus the extent of questions to 5. I could only seem to edit to 6 though. ;) 

- What do you think the purpose of this site is? 
- Could you find everything that you were looking for?
- Was there something missing you were expecting to see?
- Was anything too intrusive or too well-hidden?
- How did you find the layout? / Was everything organized as expected? 
- If you could change one thing, whether it is major or minor, what would be at the top of the list?

**Comment by mataharimhairi** [comment]
@awright These questions look great! Thanks for putting them together. I think they are a great starting point for some usability testing feedback. Not sure how we are going to execute the user testing, but there should also be a section to provide some general comments that are not restricted to these questions. A good question I always like to include is, would you use this tool? Do you think it produces a useful output?

**Comment by awright** [comment]
This might be obvious ;) but I was sort of seeing these as questions we would ask in an interview - not something they would fill out. So totally add that last question! Also in our #34 Meeting yesterday, we thought it might be most useful for @szymonkaliski to sit with you and see 2-3 how people use the tool. Is this something you could set up in the coming week?

**Comment by awright** [comment]
@smit1678 I reached out to Iyan (cc'd) who were the other people you suggested? I can't find the list. Thanks!

**Comment by awright** [comment]
### Interview with Iyan
- In order to search for an area of animation user goes to description first 
  - Think project screen would be link to tasking manager
<img width="238" alt="screen shot 2018-03-26 at 6 16 43 am" src="https://user-images.githubusercontent.com/78410/37900855-6e0b99ce-30bd-11e8-9e0d-8236da24469e.png">

- Dates need to be informed by the Tasking Manager
- Date works but would like date line on top of the play bar (one at the beginning and one of the end) 
- Continual issue with roads and building showing up b/c of slow of internet and buffering the layers 

### **Cannot see icons on the bottom**
- Could not find Play Button
- Live preview still working
- Doesn't see next step of share video
- Wants a Step by Step
- The share icon is not - the current looks like full screen 
- Text would be better than icon (Icons could be bigger as well) 
- Seeing delay for help overlay (connection) 

- Want to create a new visualizing 
- New Button visualization 

### Questions
- Where is the CREATE  button?
- Where is NEW button?
- Not clear would get link in Mail Client

**Comment by szymonkaliski** [comment]
My random notes from watching Iyan use the tool:

- decribe looks ok
- project - ? - not sure about this one - tasking managent project id/code?
- dates
  - describe start / end date labels - hide behind buttons with popup
  - Iyan is checking in osm tasking manager
- geography looks empty when date is changed - bug to fix
- base / highlighted - changes
- "where is 'create/new' button" - tried save - "can't find run button" (the play on bottom)
  - play is not visible
  - current date is visible and ok
  - progress bar should show a start date and end date
- problems with slow connection
- style
  - "highlighted" / "base" - make them more distinct
  - "'highlighted' are not appearing?"
- there's no issue wiht waiting for visualization to be made - there's no need for real time 
  - play could potentially buffer
  - make a button "create a visualization" / "new"
- flow: describe -> date -> style -> play
  - wrong icon / share button - text -> "export"/"share"
  - looking for "export" next to view/edit
- not using sidebar hiding but might be useful for others
- searching on map should zoom to 12 when focused on something
- he expects the modal to be more visible - these are the option he'd be looking for

**Comment by szymonkaliski** [comment]
UX problems:

1. not seeing changes live - this is a bug that new update fixes (2018-04-03), I think this caused some confusion for both testers and trickled into other areas of testing
2. problems finding "share"
3. "save" and "view" in different place than "share"
4. problems finding "play"
5. no info that export to MP4/GIF is happening
6. unclear how base/highlight works for styles

Possible solutions:

- [x] 1. - already solved
- [ ] 2. - needs UI/UX changes
- [ ] 3. - needs UI/UX changes
- [ ] 4. - needs UI/UX changes
- [ ] 5. - popup informing user that animation is generating, and link to the animation will be send over email
- [ ] 6. - more descriptions, help popups

Other improvements:

- predefined styles (combinations of map background + buildings/roads colors)
- loading AOI boundary(?)
- animation speed control

**Comment by awright** [comment]
@szymonkaliski when you say "needs UI/UX changes" are you expecting something from us or want to discuss tomorrow?

**Comment by szymonkaliski** [comment]
@awright we'll prepare some sketches and we should chat tomorrow as well I think :) - sorry, forgot to mention that

**Comment by szymonkaliski** [comment]
So here's proposal for some quick wins for UX:

0. starting page will have additional "create visualization >" big button below the intro text, so user doesn't have to look for "new" button at the top (nod visualized in the mockups below, but hopefully easy to imagine)
1. updated top bar: New/Save/Share are near each other and easier to find, View/Edit also clustered together, and help at far right (help could be dropdown menu with "about" and "tutorial") - this makes the top bar similar to most online tools/menubars
2. added scale and legend to the map in lower right corner
3. added help tooltips guiding user through the app; first time user opens the app, they show up one-by-one guiding the user, after first use they are hidden behind the "?" icons (they could contain detailed info and gifs of how to use the tool)
4. switched sidebar from tabs, to showing everything with scrollable view, this makes sure that date span is always visible; we could also make the detailed date picker appear in popup, and only show the dates by default, to further save some space
5. the "view"/"shared-url" sidebar stays the same (non-editable fields with description, date span, etc..., like we have now)
6. style edit has some pre-defined colours for user to start from, and "custom" option where user can edit the colours, this will give the user some nice defaults to browse through, and allow to play with colours if he chooses to do so

This should fix most of the UX problems in my view, but happy to discuss the proposed changes in the meeting later today.

Below screens show the sidebar in default, and then scrolled down position:

![1](https://user-images.githubusercontent.com/1040420/38305706-1bd242a4-380e-11e8-87c1-a56f6ef50d20.jpg)
![2](https://user-images.githubusercontent.com/1040420/38305707-1bf27f42-380e-11e8-8f3e-914431b4966d.jpg)

**Comment by szymonkaliski** [comment]
@smit1678 idea for simplified view:

![screen shot 2018-04-04 at 16 28 40](https://user-images.githubusercontent.com/1040420/38316904-1d2c6bfc-382c-11e8-96b2-4e4b466f19bd.png)

This should be "default" view in edit mode, with additional fields, style, etc... appearing after entering "advanced" settings.

We agreed this is a good next step after implementing UX updates from previous comment here; we will propose a design for this first, and then implement this second (more info in ____)

**Comment by awright** [comment]
Notes from testing with Russ Duffner:
**His Flow**
- Completed describe fields immediately and went to full screen and then "played" animation
  - Did not go to Date or Style settings
- Did not use the search bar but rather panned to AOI
- Long wait for animation 
- Would be most interested in MP4
- Want to see edits from last month 
- Thinks Learn link would go to learnosm

**Issues (& Suggestions)**
- The zoom level was very close to for him - he could not do a country or we wondered about Colorado scale
- Back button went to the ocean which is current style is all black. Suggested a lighter palette with blue ocean
- Would like to see immediate change when he changes styles
- Once chooses a color picker, would prefer that is close
- Long wait for animation to play. Not sure what the right date range to select. Would like to preview frame forward in timeline. 
- We discussed having some sort of progress bar to give some indication that things were loading in cache
- Did not click the VIEW link. needed to be prompted and wasn't sure it's use - suggested that it have a list of all saved animations - perhaps one users had marked as public in the save workflow. 
- Wanted to change date from the playbar
- When viewing the latest wireframes he actually said he liked the tabs as much as the single settings panel.

**Comment by szymonkaliski** [comment]
Here's proposed design for @smit1678 idea for simplified view, first two images are close to the original idea, and image three is proposition to keep the title for visualization visible, and allow color theme setting (probably without "custom" option in this view).

"Advanced" would lead user to what we are currently working on in the sidebar, I also feel there should be an option to move back to "simplified" from there.

Maybe also this would be a good use for tabs, so we have "Basic Settings" | "Advanced Settings" on the top.

Open to hear your ideas!

![1](https://user-images.githubusercontent.com/1040420/38367624-7efef734-38e3-11e8-876b-991a49817247.jpg)
![2](https://user-images.githubusercontent.com/1040420/38367625-7f1d1af2-38e3-11e8-9d6b-2d14eae8e30c.jpg)
![3](https://user-images.githubusercontent.com/1040420/38367626-7f3877a2-38e3-11e8-84fd-1c0b1920c549.jpg)

Just to make sure everyone is on the same page, we will be implementing that after we are done with current batch of UX changes, so we have some time to discuss.

**Comment by awright** [comment]
this is really nice @szymon! two comments

1. i think we should have the advance option link towards the top. i think
one could miss it on the bottom.

2. what do you mean by “custom” in the “select changes” dropdown?

**Comment by szymonkaliski** [comment]
> 1. i think we should have the advance option link towards the top. i think one could miss it on the bottom.

Sure, I'm thinking the same!

> 2. what do you mean by “custom” in the “select changes” dropdown?

I mean for start you will have option for "last week", "last month", "last two months", "last three months", and then "custom" where you can specify any dates that you might need.

**Comment by awright** [comment]
cool. makes sense of both. thanks for the clarification!

**Comment by mataharimhairi** [comment]
@szymonkaliski @awright I did a walk through demo of the tool with Charlotte and Faizal from DMI, with a couple of comments/feedback: 

1. In regards to the limited zoom levels, I think providing the users with more information, specifically in regards to installing a local copy of the tool to try and produce animations for zoom levels 0-11. This might just be a little info box with a link to the README section on GitHub.
2. Where the play button sits, continues to confuse new users. They instinctively look for the play button underneath the settings on both the SIMPLE and ADVANCED tabs. Perhaps an arrow pointing to the play button on the bottom bar would help?
3. Selecting the dates is slightly confusing. Charlotte thought it was sufficient to select a month and year, not realising that a specific day had to be chosen. Can we default the tool to choose the first day of the month, unless specified by the user?
4. Can we add a monthly and yearly interval. This is a good suggestion, as she wanted to check the data mapped in a remote area of Indonesia, but wasn’t exactly sure of the dates. So she created a visualisation for a 15 year timespan, which doing weekly intervals is very slow.
5. Perhaps a way to try and reduce the amount of users doing this (long timespans) would be to provide a link and some information to OSM Analytics on the 'About page'. This way the user can determine there area of interest and dates through OSMA, and then plug them in to the Visualize Change tool.

Overall they were very happy with the tool! Especially to hear that it has been designed for future expandability, such as having the functionality for zoom levels 0-11 commented out in the code.
