### ISSUE TITLE
Design Feedback

### ISSUE THREAD

**Issue by awright** [hotosm/visualize-change#33]
This is initial design and layout feedback for the Animation Prototype. Still a work in progress and just idea. I'd like to review as a group before we prioritize anything to implement. 

https://docs.google.com/document/d/1KIiicY3hbdJBtyuGM5FjQOPLZ3uxMN6zhHHMTS3AWNM/edit?usp=sharing

**Comment by szymonkaliski** [comment]
Hey, thanks for this doc, but this feels like a design feedback to current version on the dev server, where we are working on functionality and not the "look" of elements (this comes from some library, and we are not focusing on it currently, we are just using some elements to build up the functionality). 

For the design feedback, we were hoping to have comments to: https://github.com/hotosm/visualize-change/issues/27#issuecomment-369611290 which is a preview of how the tool could look like (look = button styles, colors, etc...).

I know both functionality and look are connected here, but maybe let's finish adding all the functionalities to the tool, and then discuss how exactly it should be styled, like we agreed?

**Comment by awright** [comment]
These were not work priorities but I point of discussion for, as you say "a
preview of how the tool could look like (look = button styles, colors,
etc...)." I was very specific about color, buttons, and font, for example.
So I think we need to talk further.

I'd like to start the meeting today with a review of functionality that is
still missing. To me it looks like everything is mostly complete and in a
place for testing.

**Comment by awright** [comment]
Prioritizing work as specified in #34 Today's Meeting. We can use this as reference for additional feedback from testing etc.
