### ISSUE TITLE
Bug Review

### ISSUE THREAD

**Issue by awright** [hotosm/visualize-change#38]

**Comment by awright** [comment]
- Zooms for creating animations not always set for zoom 12. 
- Filtering is not working on zoom levels that are not equal to 12

**Comment by szymonkaliski** [comment]
* filtering when map is in overzoomed state removes the tile/layers - something might be wrong with mapboxgl...
* second search is not brining users to proper zoom level (to reproduce: search berlin, layers appear, search paris, and you get "zoom in" message)
