### ISSUE TITLE
Offline Rendering

### ISSUE THREAD

**Issue by awright** [hotosm/visualize-change#4]
Documented research for offline rendering approach. Note the #3 Alpha Version should implement basic offline functionality.

**Comment by szymonkaliski** [comment]
Offline render is done (not polished but working). It's using Electron and xvfb inside of ubuntu docker container, and working pretty well I'd say. There are some magic invocations to keep in mind, and it's bit hard to debug when running inside of docker, so `renderer` has an option to be run on the host machine for development.

**Comment by awright** [comment]
@szymonkaliski awesome! have any relevant links here for posterity?

let's document this in the #1 tech approach and final #15 documentation. then we can close this ticket out.

**Comment by awright** [comment]
offline reference added to rendering section to readme

**Comment by szymonkaliski** [comment]
Just to avoid some confusion that I didn't get a chance to explain in the meeting: "offline renderer" is the same thing as "renderer" and is a pice of code that creates final mp4 based on some input data (date span, lat/lng, etc...). This part is already done.

This also relates to #6 and #8 which are basically about the parameters that this piece of code gets to do the rendering. It will evolve together with Frontend map, so both rendered mp4 and preview map on the frontend, look exactly the same.
