### ISSUE TITLE
Text update to communicate supported zoom levels

### ISSUE THREAD

**Issue by smit1678** [hotosm/visualize-change#40]
Related to https://github.com/hotosm/visualize-change/issues/39#issuecomment-382300750, proposing to update the text for the zoom level support. Can we switch to more positive, actionable language? 

Suggestion: `Zoom in to see data. Take me to the supported zoom levels.` 

![hot mapping vis 2018-04-18 13-45-16](https://user-images.githubusercontent.com/796838/38930113-0cb55afc-430f-11e8-8b32-9b431fd0490d.png)

**Comment by szymonkaliski** [comment]
done with https://github.com/hotosm/visualize-change/commit/3e80af784a7249ae1eb986a11cfa4981811e048c

dev server is updating, should be online soon
