### ISSUE TITLE
Videos Not Coming Through

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/visualize-change#44]
Unfortunately the MP4 videos are not coming through. I created the visualisations, saved them and then selected share, filling out my email and getting a confirmation response that it is in the queue. 

However I waited more than 24 hrs and still haven't received anything. Will try creating more today, as well as selecting the GIF option to see if that is more successful. Really liking the results for the saved URL animations though!

**Comment by hoffmannjan** [comment]
It would be super helpful if you could share with us URL with created animation that you wanted to export as MP4 so we can reproduce this situation.

**Comment by mataharimhairi** [comment]
hello @hoffmannjan I created this one yesterday and shared the MP4 video to my email address:

http://dev.visualize-change.hotosm.org/view/51

let me know if you would like to create more for you to try. thank you!

**Comment by szymonkaliski** [comment]
This should be fixed now, keep in mind that we had to reset the DB, so old saved views are not accessible.
