### ISSUE TITLE
Help Prompts

### ISSUE THREAD

**Issue by awright** [hotosm/visualize-change#45]
Draft for all the Help prompts in the interface. This includes the main menu, basic tab, and advanced. 

@szymonkaliski I think it's good to start adding to the interface but I encourage everyone to please review! cc @smit1678 @mataharimhairi 

https://docs.google.com/document/d/1aG_10WQn0H-RnxGoEscF_zEuuz-cCQqfXIYEDTf2edQ/edit?usp=sharing

#29 Project Timeline

**Comment by szymonkaliski** [comment]
Help was added to the app, if you want to update texts in the future, you can access them here: https://github.com/hotosm/visualize-change/blob/master/frontend/src/constans/help.js
