### ISSUE TITLE
Issues with Share Functionality

### ISSUE THREAD

**Issue by awright** [hotosm/visualize-change#46]
@mataharimhairi and I are seeing unexpected results with the share functionality that I'm not sure we've seen before. I put together my steps in the document below. 

https://docs.google.com/document/d/15MUOW1VlksbUZw3vO9UCYKumayNjBqsG97w1BG7zsNw/edit?usp=sharing

If others are experiencing this, it's a definite bug. So let's resolve. cc @szymonkaliski

**Comment by awright** [comment]
Also, to note: I have not received an email with the saved animation.

**Comment by szymonkaliski** [comment]
This should be now (https://github.com/hotosm/visualize-change/issues/29#issuecomment-385456807) fixed!
