### ISSUE TITLE
Visualisations are not being E-mailed

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/visualize-change#52]
Unfortunately the visualisations created, saved and shared to my e-mail are not coming through. They were working early last week, but seem to be failing now? Tyler has also tried to create, save and share some to himself, without receiving anything either.

**Comment by szymonkaliski** [comment]
I was updating the test server yesterday with bugfixes, maybe he was unlucky enough for the message to the API to get lost somewhere while it was down for a bit.

MP4/GIF generation should work (**tested here today**), so if you could try again, that would be helpful.

If it doesn't work, then please provide the URL to the saved animation so we can test.

**Comment by mataharimhairi** [comment]
@szymonkaliski @awright I just tried it again, and it successfully emailed the visualisation to me! thank you so much for looking into this. going to close the issue.

**Comment by awright** [comment]
I also received an email MP4 of the animation though have not yet been able
to review quality. Will reopen ticket if there is a problem.
