### ISSUE TITLE
Rendering API v1

### ISSUE THREAD

**Issue by awright** [hotosm/visualize-change#6]
To keep track of rendering work as applied to the #5 Gunung Agung animation.

**Comment by szymonkaliski** [comment]
Not sure what this relates to really? Is that in regards to Offline Renderer (#4)? If so then I don't think we need two issues for that?

**Comment by awright** [comment]
Let's discuss at Wednesday meeting. #21 

For reference, I was looking at component 2 & 3 API rendering deliverables in the contract.

**Comment by szymonkaliski** [comment]
I think we can safely close this?
