### ISSUE TITLE
Animations are not being emailed

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/visualize-change#65]
I've tried several times now over the last couple of weeks and none of the animations I create, save and share are being emailed to my address. Here is one of the most recent attempts:

http://dev.visualize-change.hotosm.org/view/72

**Comment by awright** [comment]
@dakotabenjamin @smit1678 can we look into this? it also blocks us on announcing the tool.

**Comment by smit1678** [comment]
Yes, but let's hold off until @dakotabenjamin gets our new deployment and production setup running to test and recreate the issue.

**Comment by awright** [comment]
I am doing OC animations now. Saving them and sharing them to my email
account. Should I hold off?

**Comment by smit1678** [comment]
Yeah because these will be lost once we switch over to the production deployment.
