### ISSUE TITLE
Frontend UI v1

### ISSUE THREAD

**Issue by awright** [hotosm/visualize-change#7]
For tracking frontend + server API work as applied to the #5 Gunung Agung animation.

**Comment by szymonkaliski** [comment]
Per our meeting today, to implement Frontend Alpha version we would like some comments / "green light" on the Wireframes here (https://github.com/hotosm/visualize-change/issues/2#issuecomment-361926613).

**Comment by szymonkaliski** [comment]
I think we can safely close this?
