### ISSUE TITLE
Video Renderer download link loads as text 

### ISSUE THREAD

**Issue by dakotabenjamin** [hotosm/visualize-change#73]
May be due to nginx configuration

**Comment by dakotabenjamin** [comment]
@szymonkaliski any idea why this isn't working? Try yourself- visualize-change-dev.hotosm.org, try to save a rendering and make sure to choose mp4 format.

**Comment by szymonkaliski** [comment]
Hmm, I just generated the video, copied the URL and it downloaded mp4..? One thing that you might want to do, is when setting `SERVER_DOMAIN` start with `http` so the link is clickable :)

**Comment by dakotabenjamin** [comment]
What os and browser are you using?

**Comment by szymonkaliski** [comment]
macOS 10.13.6 w/ Google Chrome 68.0.3440.84

**Comment by smit1678** [comment]
Interesting. Yes, I can reproduce that this downloads fine in Chrome. But here's what it looks like in Firefox: 

<img width="948" alt="mozilla firefox 2018-08-04 16-08-59" src="https://user-images.githubusercontent.com/796838/43674599-c837b946-9800-11e8-9249-c2ebe2357ec1.png">

**Comment by szymonkaliski** [comment]
Yeah so it looks like the `Content-Type` is set to `text/plain`, I think we should include `mime.types` in nginx config, adding `include /etc/nginx/mime.types;` in the `http` section should help, @dakotabenjamin could you try that?

**Comment by dakotabenjamin** [comment]
Thank you! It's fixed in https://github.com/hotosm/visualize-change/commit/8396098ca1802fb6d11fd293ef39306964401619
