### ISSUE TITLE
"Take me to supported zoom level" default bring me to sea

### ISSUE THREAD

**Issue by iyan31** [hotosm/visualize-change#80]
When I just opened the website and then I clicked "Take me to supported zoom level". It would direct me to light grey sea, which initially I thought the website is still loading. It would be great if the default is in a city or add a small [inset map](http://wiki.gis.com/wiki/index.php/Inset_Map)

**Comment by dakotabenjamin** [comment]
It's probably taking you to 0,0. I think when your location is enabled it will bring you to your location, but for users who don't have location enabled, this is a good idea. It should be a simple fix to set the initial map location, although what location that should be I don't know
