### ISSUE TITLE
Not receiving animations via email

### ISSUE THREAD

**Issue by jessbeutler** [hotosm/visualize-change#95]
I've tried to make a few animations over the past few days but have not received any of them via email. 

Link to latest attempt: [visualize-change.hotosm.org/view/67](url)

**Comment by mataharimhairi** [comment]
@jessbeutler are you still experiencing this problem? I just tried exporting an animation as a gif which I successfully received via email.

**Comment by jessbeutler** [comment]
@mataharimhairi nope! Just tested and it's working.

**Comment by mataharimhairi** [comment]
great! will close this issue then. thanks Jess!
